# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages

apt_packages:
  - ruby-dev

before_install:
  - gem install bundle

after_success:
  - Rscript -e 'covr::codecov()'
